version: '3.9'

services:
  db:
    image: postgres:14.2
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRES_HOST=127.0.0.1
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - db_network
    restart: unless-stopped
  redis:
    image: redis:7.0.0
    networks:
      - redis_network
    restart: unless-stopped
  api:
    build:
      context: .
    command: bash -c "
        python manage.py collectstatic --noinput &&
        gunicorn api.wsgi -c gunicorn_conf.py
      "
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    volumes:
      - /tmp/static:/api/staticfiles
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    networks:
      - db_network
      - redis_network
    restart: unless-stopped
  celery:
    build:
      context: .
    command: celery -A api worker -c 3 -P gevent -l info
    environment:
      - DATABASE_URL=psql://user:password@db:5432/db
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    networks:
      - db_network
      - redis_network
    restart: unless-stopped

volumes:
  db_volume:

networks:
  db_network:
  redis_network:
