# Generated by Django 3.2.2 on 2022-07-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_offerparam_value'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productcategories',
            table='products_product_categories',
        ),
    ]
